replicaCount: 1

image:
  repository: ghcr.io/andriesh/telegram-bridge
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  BOT_TOKEN: "7348825247:AAEIENwLpaMKBVLDTURt9zJkG8FYzbHkf_Q"
  CHAT_ID: "-1003955291725"

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: bridge.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
# tls:
#   - secretName: bridge-tls
#     hosts:
#       - bridge.local

resources: {}